---
- name: Install Bind
  apt: 
    name: bind9
    state: latest

- name: Copy named.conf.local
  template: src=named.conf.local dest=/etc/bind/named.conf.local backup=yes

- name: Path for zones
  file: 
    path: "{{ ZONES_PATH }}"
    state: directory

- name: cp db.sec.cuc.edu.cn
  template: src=db.cuc.edu.cn dest={{ ZONE_FILE_PATH }} backup=yes
  notify: 
    - dns restart
  