---
- name: Install vsftpd
  apt:
    name: vsftpd
    state: latest

- name: Create directory for anonymous users
  file: 
    path: "{{ ANONY_DIR }}"
    owner: "nobody"
    group: "nogroup"
    state: directory

- name: Add group for user
  group:
    name: "{{ user }}"
    state: present

- name: Add user cuc
  user:
    name: "{{ user }}"
    group: "{{ user }}"
    password: "{{ user_pwd }}"

- name: Create ftp home directory for the local allowed user
  file:
    path: "{{ USER_DIR }}" # creates={{ USER_DIR }}
    owner: "nobody"
    group: "nogroup"
    mode: a-w
    state: directory

- name: Create directory for the user in white lists
  file: 
    path: "{{ USER_DIR_W }}" # creates={{ USER_DIR_W }}
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- name: Create file vsftpd.userlist 
  copy: 
    content: "{{ user }}"
    dest: /etc/vsftpd.userlist
    force: no
    owner: root
    mode: 0666

- lineinfile: 
    path: /etc/vsftpd.userlist
    line: 'anonymous'

- name: Copy config file 
  template: src=vsftpd.conf dest=/etc/vsftpd.conf backup=yes
  notify:
    - restart vsftpd